# Generated by Django 3.2.5 on 2021-07-23 06:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'FULL TIME'), ('PART_TIME', 'PART TIME')], default='FULL_TIME', max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
